### PR TITLE
Add FFMpeg HTTP Live Streaming support

### PR DESCRIPTION
**Pull request by brownard**
I find the VLC encoding a bit ropey so I've added FFMpeg support for HLS streams.

I also fixed a potential fatal exception when writing a channel logo to the cache if you have more than one channel with the same name

### CODE REVIEW

**Comment by DieBagger** [comment]
Awesome, how does ffmpeg HLS perform compared to VLC HLS ?

**Comment by brownard** [comment]
The encoding is quick and the video quality is perfect for me (I was getting a lot of artifacts with VLC), I think it's definitely the way to go.

**Comment by oxan** [comment]
Awesome, thanks a lot! This is something I've been wanting to implement myself eventually, but I haven't got time for it yet. It's probably too late to push it into 0.5 though, but we'll merge it as soon as we start development for 0.6.

I've a few comments on the code though, which I've put inline below.

**Comment by brownard** [comment]
Changes as requested (hopefully!)

**Comment by oxan** [comment]
Awesome, thanks!

I'll merge it when we've branched 0.6, probably in around 2 weeks.

**Comment by oxan** [comment]
Merged, thanks a lot!

**Pull request merged**
