### PR TITLE
Fixes, improvements and rework ... based on regeszter changes ... 

### PR DESCRIPTION
**Pull request by andrewjswan**
More info - https://forum.team-mediaportal.com/threads/pre-0-7-beta-mpextended-webmp-bootstrap-skin-by-ajs-hard-way.139992/

### CODE REVIEW

**Comment by oxan** [comment]
Hi! Great to see people are still interested in the work we did years ago. It's been a while. 

As you've probably seen none of us are still actively working on this project. Instead of me just merging this, do you want to be added (as admin) to the GitHub organization? That way you can (along with any other interested devs) take care of the project, and maybe even put out a new release ;)

**Comment by andrewjswan** [comment]
> Hi! Great to see people are still interested in the work we did years ago. It's been a while.
> 
> As you've probably seen none of us are still actively working on this project. Instead of me just merging this, do you want to be added (as admin) to the GitHub organization? That way you can (along with any other interested devs) take care of the project, and maybe even put out a new release ;)

Hi! I just wonder how it works, I understand a little, in C #, Razor, MVC. Therefore, adding new features takes me a lot of time, but it is an interesting exercise for the mind. It is a pity that few people are interested in it and there is no one who understands streaming, if someone helped transfer the streaming from flash to modern tracks, it would be great. As for administration, it would be great if the repository was in a single place, and not look for it in all forks.

**Comment by oxan** [comment]
Yeah, it's an interesting exercise, lots of things I've learned while working on MPExtended. The streaming has always been a problem, I never got it working quite as well as I wanted either.

> As for administration, it would be great if the repository was in a single place, and not look for it in all forks.

Ok, I've invited you to the MPExtended team here, so you should be able to manage the repository now! :)

**Comment by andrewjswan** [comment]
@oxan can you help with playback video and recording in WebMP on Chrome (html5)?

Thanks for invite :)

**Comment by oxan** [comment]
No, it's been way too long ago for me to be able to say anything sensible about it, and I haven't really followed the developments in that space since then. (I actually don't use MediaPortal anymore, so that's also a complicating factor).

**Comment by andrewjswan** [comment]
@oxan Here the question is no longer in the Media Portal, but in the WEB player which could play streams in Chrome. I tried some free options, but so far without success. :)

**Comment by andrewjswan** [comment]
Will be added later to the correct brunch.

**Pull request closed without merging**
