### PR TITLE
Fix downloadable playlist for music albums

### PR DESCRIPTION
**Pull request by Ollienator**

### CODE REVIEW

**Comment by oxan** [comment]
Awesome, thanks!

**Comment by Ollienator** [comment]
Argh.  Adding the continuationId actually breaks the playlist.  VLC and WMP just skip through the list but nothing plays.  If I remove the parameter, it plays fine. 
I have noticed that the flash based album player doesnt use the continuationId either.
Should I wait for a fix in the transcoder part or remove the parameter for now?

EDIT: Sorry, my fault.  It was an error in my local setup.  It works just fine.

**Comment by oxan** [comment]
> I have noticed that the flash based album player doesnt use the continuationId either.

Good catch, created #262 for it.

**Comment by Ollienator** [comment]
I added the ContinuationId parameter for the album player in commit ec6af5e in my fork.

**Comment by oxan** [comment]
Awesome! I'll merge it when I'm at a computer with MPExtended cloned tomorrow.

**Comment by Ollienator** [comment]
Great!  Could you have a look at commits e593cbbf40 and 441e1ec8e7 as well please?
They deal with using the sorting fields of the MP-TVSeries/MovingPictures databases (i.e. sorting "The Big Bang Theory" under 'B' instead of 'T') in MAS and a small issue with the cache headers in WebMP, respectively.

**Comment by oxan** [comment]
I have pulled 441e1ec and ec6af5e into the master of MPExtended, thanks!

I don't know what I'm going to do with e593cbb yet. @DieBagger opposes the replacement of the current title sort option, instead of adding another one. I'm personally not really sure whether it's a good idea to send the sort-title as another field to the client, instead of only using it internally. That might need a lot more work to implement though. I'm going to think a bit about this ;)

**Comment by Ollienator** [comment]
I know, I thought about just adding another sort option, too. ;-)
The reason why I chose to use the sort title internally only, was to make the sort order consistent with mediaportal itself, without requiring client side changes.  
The inconsistency with mediaportal was what got my attention in the first place:  The TV show list in WebMP looked different from the list on my HTPC - my shows (and movies) weren't in the order I expected.

**Pull request merged**
