### PR TITLE
WebMP: add method for viewing tvshow details in season view

### PR DESCRIPTION
**Pull request by puenktchen**
Hi Oxan,

Not nedded by default skin, but maybe by others (mine)

### CODE REVIEW

**Comment by oxan** [comment]
Could you set your git to do automatic line conversion (git config core.autocrlf true) and then try to commit again? Currently you rewrite the whole file in your commit, which makes the diff a bit hard to read.

**Comment by oxan** [comment]
I think it's a lot better idea to just change all occurences of Basic with Detailed in WebMP. We don't gain anything at all by using the Basic variants in WebMP.

**Comment by puenktchen** [comment]
Should i try it or will you do it?

 

-----Original Message-----

**Comment by oxan** [comment]
I'd appreciate if you could try it, as it will probably take until Friday until I'll get at it :)

**Comment by puenktchen** [comment]
Pure accident but i'm on a business trip until weekend...

 

-----Original Message-----

**Comment by puenktchen** [comment]
As this doesn't hurry i would go for it next weekend.
There are enough issues leftover, they need more attention by you.

**Pull request closed without merging**
