### PR TITLE
WebMP: Changed all possible "Basic" calls to "Detailed"

### PR DESCRIPTION
**Pull request by puenktchen**
Hi Oxan,
second try and hopfully it's okay this time...

### CODE REVIEW

**Comment by oxan** [comment]
You still missed a few occurences in the variable declarations (it should be IEnumerable<WebMovieDetailed> instead of IEnumerable<WebMovieBasic> etc); and I think it'd be nice if we could change the model declarations in the views too (the @Model lines). 

Anyway, looks good, and I'll either merge it when you fix those or when I've a bit more time to fix them up myself (somewhere this week probably).

**Comment by puenktchen** [comment]
Give me the chance. I will look for the "forgotten".

 

-----Original Message-----

**Comment by oxan** [comment]
Looks good! I've merged it :)

You still have some whitespace changes btw (StreamController.cs). That's not really a problem, but it makes reviewing a bit harder.

**Comment by puenktchen** [comment]
Yea i've seen it also. That must come from my Visual Studio - it's a beast...

**Pull request merged**
