### PR TITLE
WSS: Rewrite VLCWrapper in c#

### PR DESCRIPTION
**Pull request by Ollienator**
Fixes issues with UTF8 encoded characters in media file names (e.g. the umlaut in "Björk")

### CODE REVIEW

**Comment by oxan** [comment]
In any case, this isn't the way we'll be going to fix this in 0.5. Way too big change. I actually already knew about the UTF8 encoded characters, see issue #197. We need to do some wchar conversion magic in VLCWrapper. Not too hard, but I just need to have a bit of time to fix it. 

Anyway, I'm not really sure I actually want to rewrite VLCWrapper in C#. Using P/Invoke is an awful lot slower than a native C++ program. Something in the order of magnitude of being 10000 times slower. Since we are calling VLC twice a second now and it'll become more in the future, I'm afraid it'll start to hurt transcoding performance. 

Also, if we're going to rewrite it in C#, we'll just add it as another project to the MPExtended solution and remove the binaries from the source all together, instead of putting it in a separate solution (and target .NET 4 instead of .NET 4.5).

**Comment by Ollienator** [comment]
Ok understood.  What do you think about posting the .NET VLCWrapper binary only in the mp forum instead to have a workaround until this gets fixed properly?
Will do some cleaning up (.NET 4.5, doh!) anyway.

**Comment by oxan** [comment]
Well, of course you can post in the forums what you want. I'm not sure how useful it'll be, as we'll fix it before the 0.5 release anyway. 

Also, I'm not saying that we won't rewrite VLCWrapper in C#. I just want to have some tests done before doing it.

**Comment by Ollienator** [comment]
Yep, got it.  I just thought I understood that P/Invoke wasn't an option for you at all due to speed considerations.  Regarding this, I have clocked the P/Invoke call to libvlc_media_player_get_time() - which would be the only P/Invoke call running inside the loop - at over 4 million calls per second.  So I guess the bottleneck would more likely be formatting and parsing the output (not sure, havent timed these).
I am also testing changes to the original vlcwrapper.cpp using wchar_t and WideCharToMultiByte() to do the UTF-8 encoding for LibVLC.  So far I haven't seen any issues, but I will try different scenarios later today.

**Comment by oxan** [comment]
>  at over 4 million calls per second.

Hmm, that surely sounds acceptable. 

> I am also testing changes to the original vlcwrapper.cpp using wchar_t and WideCharToMultiByte() to do the UTF-8 encoding for LibVLC

Yeah, that's exactly what I wanted to do; just didn't get to it yet ;)

Thanks for your work, I'll review it a bit more in-depth tomorrow.

**Comment by Ollienator** [comment]
I have added two commits (8652888 and c3f64c1) to my fork that include the vlcwrapper.cpp changes and .NET port, respectively.  
The .NET part is a separate project now without binaries, the code contains the commented out "benchmark" that I used to clock the performance.  
I have tested the modified version of vlcwrapper.cpp using various audio and video sources and it works on my system without any flaws, but I am not at all a c++ guy.  More testing needed, obviously. ;-)

**Comment by oxan** [comment]
Awesome, thanks!

I've created the fix-vlcwrapper-utf8 branch in the MPExtended Git, with your fix to the C++ version in it (+ some cosmetical changes). It seems to work fine for me, but I want to do some more testing tomorrow, and merge it if it doesn't cause any problems. 

The .NET version looks good too. I want to take a more detailed look at its performance after the 0.5 release, and if that works out I'm probabyl going to merge it too. Sounds good?

**Comment by Ollienator** [comment]
Sounds perfect ;-)

**Comment by oxan** [comment]
Merged!

**Pull request closed without merging**
